import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import connectDB from "./config/db.js";
import Document from "./models/Document.js";
import User from "./models/user.js";
import jwt from "jsonwebtoken";
import { protect } from "./middleware/authMiddleware.js";

dotenv.config();

const app = express();

connectDB();

app.use(cors({
  origin: ["http://localhost:5173", "https://interactive-docs-ayudev.vercel.app", "https://interactive-docs-io8v.vercel.app"],
  credentials: true,
}));
app.use(express.json());

app.get("/", (req, res) => {
    res.json({
        message: "API is running",
    });
});

app.get("/dashboard", (req, res) => {
  res.redirect("http://localhost:5173");
});

const generateToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET || "defaultsecret", {
    expiresIn: "30d",
  });
};

// POST /api/auth/signup
app.post("/api/auth/signup", async (req, res) => {
  try {
    const { name, email, password } = req.body;
    const userExists = await User.findOne({ email });
    if (userExists) {
      return res.status(400).json({ message: "User already exists" });
    }
    const user = await User.create({ name, email, password });
    if (user) {
      res.status(201).json({
        _id: user._id,
        name: user.name,
        email: user.email,
        token: generateToken(user._id),
      });
    } else {
      res.status(400).json({ message: "Invalid user data" });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// POST /api/auth/signin
app.post("/api/auth/signin", async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (user && (await user.matchPassword(password))) {
      res.json({
        _id: user._id,
        name: user.name,
        email: user.email,
        token: generateToken(user._id),
      });
    } else {
      res.status(401).json({ message: "Invalid email or password" });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// GET documents (supports optional ?collectionName= query param)
app.get("/api/documents", protect, async (req, res) => {
    try {
        const { collectionName } = req.query;
        let query = { userId: req.user._id };
        if (collectionName) {
            query.collectionName = collectionName;
        }

        let documents = await Document.find(query);
        res.json(documents);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// GET a single document by ID
app.get("/api/documents/:id", protect, async (req, res) => {
    try {
        const doc = await Document.findOne({ _id: req.params.id, userId: req.user._id });
        if (!doc) return res.status(404).json({ message: "Document not found or unauthorized" });
        res.json(doc);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// GET export a collection to markdown
app.get("/api/collections/:collectionName/export", protect, async (req, res) => {
    try {
        const { collectionName } = req.params;
        const documents = await Document.find({ collectionName, userId: req.user._id });
        
        let markdownString = `# Collection: ${collectionName}\n*Generated by iDOCS*\n\n---\n\n`;
        
        if (documents.length === 0) {
            markdownString += `*This collection is currently empty.*\n`;
        } else {
            documents.forEach(doc => {
                markdownString += `## Tag: ${doc.tag?.tagTitle || 'Untitled'}\n`;
                if (doc.createdAt) {
                    markdownString += `**Created at:** ${new Date(doc.createdAt).toLocaleDateString()}\n\n`;
                } else {
                    markdownString += `\n`;
                }
                markdownString += `${doc.desc || ''}\n\n`;
                markdownString += `---\n\n`;
            });
        }
        
        res.json({ markdown: markdownString });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// POST a new document
app.post("/api/documents", protect, async (req, res) => {
    try {
        const { desc, filesize, tag, collectionName } = req.body;
        const newDoc = new Document({
            userId: req.user._id,
            desc,
            filesize,
            tag,
            collectionName: collectionName || "General"
        });
        const savedDoc = await newDoc.save();
        res.status(201).json(savedDoc);
    } catch (error) {
        res.status(400).json({ message: error.message });
    }
});

// PUT (update) an existing document
app.put("/api/documents/:id", protect, async (req, res) => {
    try {
        const { desc } = req.body;
        const updatedDoc = await Document.findOneAndUpdate(
            { _id: req.params.id, userId: req.user._id },
            { desc },
            { new: true }
        );
        if (!updatedDoc) return res.status(404).json({ message: "Document not found or unauthorized" });
        res.json(updatedDoc);
    } catch (error) {
        res.status(400).json({ message: error.message });
    }
});

const PORT = process.env.PORT || 5000;

if (process.env.NODE_ENV !== 'production' || !process.env.VERCEL) {
    app.listen(PORT, () => {
        console.log(`Server listening on port ${PORT}`);
    });
}

export default app;